window.INTERVIEW_EXAMPLES = [
  {
    id: "embedding-pairs",
    title: "Pair embedding IDs to a target score",
    eyebrow: "Coding pattern 01",
    topic: "coding",
    level: "basics",
    minutes: 8,
    roles: ["AI engineer"],
    summary: "Use a hash map to trade memory for a single pass, then explain the duplicate-value edge case.",
    prompt: "Given integer embedding IDs and a target, return the indices of two IDs whose sum equals the target. Each input has exactly one solution, and an index may not be reused.",
    questions: ["What information do you need from earlier elements?", "When should the current ID enter the map?", "What happens when both values are equal?"],
    hints: ["For each ID, calculate the complement.", "Store values you have already visited, not future values."],
    solution: "Scan once. Before storing the current value, look up target minus the current value. If it exists, return the stored index and the current index. Checking first prevents one element from matching itself.",
    code: `def pair_ids(ids, target):\n    seen = {}\n    for index, value in enumerate(ids):\n        complement = target - value\n        if complement in seen:\n            return [seen[complement], index]\n        seen[value] = index\n    raise ValueError("No valid pair")`,
    analysis: "Time O(n); space O(n). A nested-loop answer uses O(1) extra space but O(n²) time.",
    trap: "Inserting before checking can incorrectly reuse the same index when target is twice the current value.",
    followUp: "If the stream does not fit in memory, which guarantees would you relax or what external state would you introduce?",
    transfer: "When a pairwise search asks whether a complementary value has appeared, reach for an index keyed by that value."
  },
  {
    id: "inference-windows",
    title: "Merge overlapping inference windows",
    eyebrow: "Coding pattern 02",
    topic: "coding",
    level: "intermediate",
    minutes: 12,
    roles: ["AI engineer", "Senior AI engineer"],
    summary: "Sort intervals, preserve one active window, and state the boundary convention before writing code.",
    prompt: "A long transcript is processed in token windows represented as [start, end]. Merge windows that overlap or touch so redundant inference work is removed.",
    questions: ["Is end inclusive or exclusive?", "Does touching count as overlap?", "What invariant should the output maintain?"],
    hints: ["Sort by start, then end.", "Only the most recently merged interval can overlap the next sorted interval."],
    solution: "Define intervals as inclusive for this prompt. Sort them, seed the result with the first, then compare each next start with the active end. Extend the active end on overlap; otherwise append a new window.",
    code: `def merge_windows(windows):\n    if not windows:\n        return []\n    windows = sorted(windows)\n    merged = [list(windows[0])]\n    for start, end in windows[1:]:\n        active = merged[-1]\n        if start <= active[1] + 1:\n            active[1] = max(active[1], end)\n        else:\n            merged.append([start, end])\n    return merged`,
    analysis: "Time O(n log n) for sorting and O(n) for the scan; output can require O(n) space.",
    trap: "Merging adjacent windows without first agreeing on inclusive/exclusive bounds creates silent missing or duplicated tokens.",
    followUp: "How would you process windows that arrive already sorted as an unbounded stream?",
    transfer: "Sorting often converts a many-to-many overlap problem into a comparison with one active boundary."
  },
  {
    id: "attention-by-hand",
    title: "Calculate attention by hand",
    eyebrow: "Transformer internal 01",
    topic: "transformers",
    level: "intermediate",
    minutes: 15,
    roles: ["AI engineer", "Senior AI engineer"],
    summary: "Trace query-key similarity, scaling, masking, softmax, and the weighted value sum without hiding behind a library call.",
    prompt: "For one attention head, explain how a token query q chooses information from key matrix K and value matrix V. Then explain why scores are divided by the square root of the key dimension.",
    questions: ["Which vectors determine relevance?", "Which vectors carry the information returned?", "Where is causal masking applied?"],
    hints: ["Scores are qKᵀ.", "Mask before softmax; multiply the resulting probabilities by V."],
    solution: "Compute dot products between q and every key. Divide by √dₖ so their variance does not grow with dimension and push softmax into saturated, tiny-gradient regions. Apply any causal mask to logits, softmax across candidate positions, then use those weights to take a weighted sum of value vectors.",
    code: `scores = (q @ K.T) / sqrt(d_k)\nscores = scores + causal_mask  # 0 or -inf\nweights = softmax(scores, axis=-1)\ncontext = weights @ V`,
    analysis: "For sequence length n and head dimension d, forming attention scores is O(n²d) and the score matrix is O(n²) memory before optimized kernels.",
    trap: "Saying values determine relevance confuses addressing (Q and K) with the content retrieved (V).",
    followUp: "How do FlashAttention and grouped-query attention change the implementation or memory story without changing this conceptual equation?",
    transfer: "Explain attention as differentiable lookup: query-key scores address memory; values provide the retrieved content."
  },
  {
    id: "rag-ranking-drift",
    title: "Debug a retrieval metric that improved while answers got worse",
    eyebrow: "ML reasoning 01",
    topic: "ml",
    level: "advanced",
    minutes: 16,
    roles: ["AI engineer", "Senior AI engineer", "FDE / AI product"],
    summary: "Separate the retrieval proxy from user value, slice the regression, and design evidence that can localize the failure.",
    prompt: "A RAG team reports higher Recall@10 offline after replacing its embedding model, but users flag more unsupported answers in production. Diagnose the disagreement and propose the next experiment.",
    questions: ["Does the offline set represent current traffic?", "Is Recall@10 sensitive to rank within the retrieved set?", "Could the generator or prompt interact differently with the new passages?"],
    hints: ["Trace retrieval, reranking, context construction, and generation separately.", "Slice by query type, document age, permission group, and answerability."],
    solution: "First verify dataset freshness, labels, traffic mix, and the exact metric implementation. Compare paired old/new traces on the same queries: candidate recall, rank of the supporting passage, irrelevant-context volume, truncation, reranker scores, citation alignment, and generator output. Recall@10 can rise while useful evidence moves lower or extra distractors increase. Build an end-to-end eval with answerability, citation precision, unsupported-claim rate, and human severity labels. Run a guarded A/B or shadow replay only after the offline disagreement is localized.",
    code: `retrieval: Recall@K + MRR + NDCG\ngeneration: citation_precision + unsupported_claim_rate\nproduct: task_success + severe_error_rate`,
    analysis: "No single offline metric is the product objective. The evaluation ladder should retain component metrics for diagnosis and end-to-end metrics for release decisions.",
    trap: "Immediately tuning the generator treats a pipeline symptom without proving which stage introduced the regression.",
    followUp: "Human labels are expensive. How would you choose a small evaluation set that is still sensitive to this regression?",
    transfer: "When offline and online signals disagree, audit the population and metric, then instrument the pipeline boundary where quality may have shifted."
  },
  {
    id: "pipeline-dependencies",
    title: "Order an ML pipeline and detect a cycle",
    eyebrow: "Coding pattern 03",
    topic: "coding",
    level: "advanced",
    minutes: 18,
    roles: ["AI engineer", "Senior AI engineer"],
    summary: "Model prerequisites as a directed graph, produce a topological order, and turn incomplete output into a cycle signal.",
    prompt: "Given pipeline steps and prerequisite pairs [step, prerequisite], return one valid execution order. If the dependency graph contains a cycle, return an empty list.",
    questions: ["Which direction should each edge point?", "What identifies a step that can run now?", "How does the final order reveal a cycle?"],
    hints: ["Track each node's indegree.", "Begin with every node whose indegree is zero."],
    solution: "Build adjacency lists from prerequisite to dependent step and count each dependent's indegree. Push zero-indegree steps into a queue. Repeatedly emit one and decrement its dependents. A valid DAG emits every step; if fewer are emitted, the remaining nodes participate in or depend on a cycle.",
    code: `from collections import deque\n\ndef order_pipeline(steps, pairs):\n    graph = {step: [] for step in steps}\n    indegree = {step: 0 for step in steps}\n    for step, prerequisite in pairs:\n        graph[prerequisite].append(step)\n        indegree[step] += 1\n    ready = deque(s for s in steps if indegree[s] == 0)\n    order = []\n    while ready:\n        step = ready.popleft()\n        order.append(step)\n        for dependent in graph[step]:\n            indegree[dependent] -= 1\n            if indegree[dependent] == 0:\n                ready.append(dependent)\n    return order if len(order) == len(steps) else []`,
    analysis: "Time O(V + E); space O(V + E). DFS is an alternative but needs explicit visiting and visited states for cycle detection.",
    trap: "Creating edges in the opposite direction can still produce plausible output while reversing the prerequisite semantics.",
    followUp: "How would you schedule all currently ready steps in parallel while respecting a concurrency limit?",
    transfer: "Translate prerequisites into indegrees: zero means runnable, and unprocessed nodes expose dependency cycles."
  },
  {
    id: "document-qa",
    title: "Design a cited document Q&A service",
    eyebrow: "AI systems case 01",
    topic: "systems",
    level: "advanced",
    minutes: 20,
    roles: ["Senior AI engineer", "Lead / staff"],
    summary: "Begin with trust and evaluation, then connect ingestion, retrieval, generation, citations, and operational controls.",
    prompt: "Design an internal service that answers employee questions from company documents, cites its sources, respects permissions, and can be rolled out safely.",
    questions: ["What does a trustworthy answer mean?", "Where must authorization be enforced?", "Which failures need offline tests versus production monitoring?"],
    hints: ["Model the ingestion and query paths separately.", "Retrieval access control cannot be delegated to a prompt."],
    solution: "Start with user groups, sources, freshness, latency, and abstention requirements. Ingestion parses, versions, chunks, embeds, and indexes documents with ACL metadata. At query time, authenticate first, filter candidates by ACL, retrieve and optionally rerank, generate only from supplied evidence, and return sentence-level citations. Log versioned traces without sensitive body text. Gate launch on retrieval recall, citation correctness, unsupported-claim rate, latency, and adversarial permission tests. Add an abstain/escalate path and a kill switch.",
    code: `query → authenticate → ACL-filtered retrieval\n      → rerank → grounded generation\n      → citation validation → answer or abstain`,
    analysis: "The key trade-off is not only model quality. Chunk size, index freshness, reranking cost, ACL enforcement, and abstention policy jointly set usefulness and risk.",
    trap: "A plausible demo that retrieves globally and asks the model to obey permissions is a security failure, not an MVP shortcut.",
    followUp: "Retrieval recall is strong but employees still distrust answers. What evidence would you inspect before changing the model?",
    transfer: "For production AI design, define the failure policy and evaluation suite before optimizing the happy path."
  },
  {
    id: "fde-pilot",
    title: "Turn an ambiguous workflow into an FDE pilot",
    eyebrow: "Staff scenario 01",
    topic: "leadership",
    level: "staff",
    minutes: 18,
    roles: ["Lead / staff", "FDE / AI product"],
    summary: "Convert “add AI” into a measurable workflow intervention with a narrow integration, evaluation plan, and adoption owner.",
    prompt: "A claims operations leader asks for an AI agent to reduce handling time. You have six weeks, uncertain data quality, and strict approval requirements. Frame the pilot.",
    questions: ["Which decision or task is actually slow?", "What must remain human-controlled?", "Which metric proves workflow value rather than demo quality?"],
    hints: ["Shadow the current workflow before selecting a model.", "Prefer one reversible decision point with an explicit owner."],
    solution: "Spend discovery on claim types, queue volumes, handoffs, exception costs, data access, and approval rules. Baseline median and tail handling time, rework, and error severity. Select one high-volume, low-consequence step—such as evidence summarization with cited source fields—not autonomous claim approval. Build read-only integration first, evaluate on historical cases with operator rubrics, then run shadow mode. Pilot with a named cohort, human confirmation, audit log, rollback, weekly error review, and adoption telemetry. Expand only if time saved survives rework and serious-error guardrails remain flat.",
    code: `success = time_saved_after_rework\n          AND no_increase(severe_error_rate)\n          AND adoption_by_target_cohort`,
    analysis: "A smaller workflow wedge learns faster, reduces integration and policy risk, and produces evidence for or against agentic expansion.",
    trap: "Accepting “reduce handling time” as a complete requirement leads to optimizing a model benchmark that may not change the operation.",
    followUp: "The sponsor wants an autonomous demo for the executive review. How do you preserve trust while maintaining momentum?",
    transfer: "Forward-deployed work starts with operational truth: narrow the workflow, baseline it, choose a reversible intervention, and measure value after rework."
  }
];
